dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.0.0
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.0.0'
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
levels:
  00_hello_ethernaut: '0x4E73b858fD5D7A5fc1c3455061dE52a53F35d966'